server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  user: root
  password: root
  dbname: go_app

jwt:
  secret: your-secret-key
  expire: 24  # 小时

image_host:
  token: "4e13065e1167a6f76cd6c64b17bf5653"